### ISSUE TITLE
using a zip file

### ISSUE THREAD

**Issue by Awethentique** [yushanwebdev/react-native-country-picker-modal#1]
Thank you for forking this and maintaining it.

Downloading a zip file might not be the most efficient way to manage this in your project. You could add this repo to your project with:

`yarn add yushanwebdev/react-native-country-picker-modal`

Perhaps maybe publish it to yarn if possible?

Also the package.json is missing, therefore this fork does not get the types for typescript

**Comment by yushanwebdev** [comment]
Hey @Awethentique,

Thanks for the feedback.

yeah, that's true. I'm planning to develop a CLI tool, as mentioned in the README, to automate the entire installation feature. My plan is that rather than adding this to the user's `node_modules`, it will automatically add to the user's components folder as another component. So, the user doesn't need to create PRs or patches anymore. If you want to change something, you can do it directly in the component itself.
